{
  # Hardware bits that are not disk-layout related. The filesystem/swap
  # configuration is now generated by disko.nix, which replaces the old
  # nixos-generate-config output.
  lib,
  ...
}: {
  boot.initrd.availableKernelModules = ["virtio_pci" "xhci_pci" "usbhid" "usb_storage"];
  boot.initrd.kernelModules = [];
  boot.kernelModules = [];
  boot.extraModulePackages = [];

  nixpkgs.hostPlatform = lib.mkDefault "aarch64-linux";
}
